spring:
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    content-type: application/json
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 100
server:
  port: 8300
env: dev
