spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://master/springCloud?characterEncoding=utf-8&&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    content-type: application/json
 redis:
  host: 127.0.0.1
  port: 6379
  password:
  timeout: 100
server:
  port: 8210
girl:
  name: aa
  age: 1
env: dev
