spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/springCloud?characterEncoding=utf-8&&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
server:
  port: 8200
env: dev
girl:
  name: faker
  age: 221
