spring:
  application:
    name: product
   datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://master:3306/springCloud?characterEncoding=utf-8&useSSL=true
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://master:9000/eureka/,http://master:9001/eureka/
server:
  port: 8001

